AWSTemplateFormatVersion: 2010-09-09

Resources:
  Group:
    Type: AWS::IAM::Group
    Properties:
      Policies:
        - PolicyName: deploy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "cloudformation:*"
                Resource:
                  - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/mocking-spongebob/*"
                  - !Sub "arn:aws:cloudformation:${AWS::Region}:*:transform/*"
              - Effect: Allow
                Action:
                  - "cloudformation:Describe*"
                  - "cloudformation:ValidateTemplate"
                Resource: "*"
              - Effect: Allow
                Action:
                  - acm:*
                  - apigateway:*
                  - apigatewayv2:*
                  - logs:*
                  - lambda:*
                  - iam:*
                  - s3:GetObject
                Resource: "*"
                Condition:
                  "ForAnyValue:StringEquals":
                    "aws:CalledVia":
                      - cloudformation.amazonaws.com
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource: "arn:aws:s3:::sam-cfscripts/*"

  User:
    Type: AWS::IAM::User
    Properties:
      Groups:
        - !Ref Group
