AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  HostName:
    Type: String

  BaseDomainName:
    Type: String

  Module:
    Type: String

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub "${HostName}.${BaseDomainName}"
      DomainValidationOptions:
        - DomainName: !Sub "${HostName}.${BaseDomainName}"
          ValidationDomain: !Ref BaseDomainName
      ValidationMethod: DNS

  LogGroupGenerate:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${GenerateFunction}"
      RetentionInDays: 7

  LogGroupSlashCommand:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${SlashCommandFunction}"
      RetentionInDays: 7

  LogGroupInteractions:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${InteractionsFunction}"
      RetentionInDays: 7

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: Prod

  ApiDomainName:
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainNameConfigurations:
        - CertificateArn: !Ref Certificate
      DomainName: !Sub "${HostName}.${BaseDomainName}"

  ApiMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties:
      DomainName: !Ref ApiDomainName
      ApiId: !Ref HttpApi
      Stage: Prod

  GenerateLibraries:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.9
      RetentionPolicy: Delete
      ContentUri: ../build

  GenerateFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: !Sub "${Module}.handle_lambda"
      Runtime: python3.9
      CodeUri: ../mocking_spongebob
      Layers:
        - !Ref GenerateLibraries
      Timeout: 30
      Events:
        GenerateResource:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /{string}
            Method: get

  SlashCommandFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: slash.handle_lambda
      Runtime: python3.9
      CodeUri: ../mocking_spongebob
      Timeout: 30
      MemorySize: 128
      Events:
        SlashCommandResource:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /slack/slash
            Method: post

  InteractionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: interactions.handle_lambda
      Runtime: python3.9
      CodeUri: ../mocking_spongebob
      Layers:
        - !Ref GenerateLibraries
      Timeout: 30
      MemorySize: 128
      Events:
        InteractionsResource:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /slack/interactions
            Method: post

Outputs:
  DomainName:
    Value: !GetAtt ApiDomainName.RegionalDomainName
