AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  CertificateArn:
    Type: String

  DomainName:
    Type: String

Resources:
  LogGroupGenerate:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${GenerateFunction}"
      RetentionInDays: 7

  LogGroupSlashCommand:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${SlashCommandFunction}"
      RetentionInDays: 7

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: Prod

  ApiDomainName:
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainNameConfigurations:
        - CertificateArn: !Ref CertificateArn
      DomainName: !Ref DomainName

  ApiMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties:
      DomainName: !Ref ApiDomainName
      ApiId: !Ref HttpApi
      Stage: Prod

  GenerateLibraries:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.8
      RetentionPolicy: Delete
      ContentUri: ../build

  GenerateFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handle_lambda
      Runtime: python3.8
      CodeUri: ../mocking_spongebob
      Layers:
        - !Ref GenerateLibraries
      Timeout: 30
      Events:
        GenerateResource:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /{string}
            Method: get

  SlashCommandFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: slash.handle_lambda
      Runtime: python3.8
      CodeUri: ../mocking_spongebob
      Timeout: 30
      MemorySize: 128
      Events:
        SlashCommandResource:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /slack
            Method: post

Outputs:
  DomainName:
    Value: !GetAtt ApiDomainName.RegionalDomainName
