name: Deploy

on:
  push:
    branches:
      - main

env:
  HOST_NAME: mock
  BASE_DOMAIN_NAME: sam.wtf

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the package
        run: bin/build

      - name: Run tests
        run: bin/test

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Deploy
        run: bin/deploy
