name: Deploy

on:
  push: ~
  workflow_dispatch: ~
  schedule:
    - cron:  '0 19 1 * *'

env:
  HOST_NAME: mock.sam.wtf
  IS_THIS_HOST_NAME: is-this.sam.wtf
  HOSTED_ZONE_ID: Z0197685Z9QF1NJ2YZA4

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .tool-versions
          cache: pip

      - name: Install dependencies
        run: pip install -r dev-requirements.txt

      - name: pytest
        run: python -m pytest

      - name: isort
        run: isort --profile black --check mocking_spongebob tests

      - name: black
        run: black --check mocking_spongebob tests

      - name: pylint
        run: pylint mocking_spongebob tests

      - name: mypy
        run: mypy mocking_spongebob

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    concurrency: deploy-prod

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v5

      - name: Build the package
        run: bin/build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.DEPLOY_ROLE }}
          aws-region: ap-southeast-2

      - name: Deploy
        run: bin/deploy
